# Generated by Django 4.1.3 on 2023-09-15 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('profile_image_url', models.CharField(max_length=1000)),
                ('bio', models.CharField(max_length=500)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_public', models.BooleanField()),
                ('organizer_canceled', models.BooleanField()),
                ('invitee_canceled', models.BooleanField()),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='meetmaybeserverapi.attendee')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetmaybeserverapi.attendee')),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=55)),
                ('dress_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('hours', models.CharField(max_length=200)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetmaybeserverapi.attendee')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetmaybeserverapi.locationtype')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetmaybeserverapi.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetmaybeserverapi.event')),
            ],
        ),
    ]
